# Generated by Django 2.2.7 on 2019-11-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klooni', '0002_auto_20191118_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
    ]
