# Generated by Django 2.2.7 on 2019-11-18 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klooni', '0003_auto_20191118_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['post_date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
