# Generated by Django 2.2.7 on 2019-11-20 06:54

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('klooni', '0004_auto_20191120_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
